# Generated by Django 3.2.10 on 2022-12-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_leaderboardentry_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='username',
            field=models.CharField(default='N/A', max_length=20, unique=True),
        ),
    ]
